# Generated by Django 3.1.2 on 2020-10-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='descripyion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='descripyion',
            new_name='description',
        ),
    ]
