# Generated by Django 3.1.2 on 2020-10-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201025_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
