# Generated by Django 3.1.2 on 2020-10-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_cart_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
